In [75]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import  BernoulliNB, GaussianNB, MultinomialNB

In [76]:
data = pd.read_csv("~/Desktop/mcc20192/mlearning/tareas/tarea2/nb_data/spam.csv", header=None, delimiter=" ")

#Partición aleatoria del conjunto de datos
train_data, test_data= train_test_split(data, test_size=0.30, random_state=0)
print(len(train_data),len(test_data))
print(train_data.index)

3620 1552
Int64Index([3459, 1385, 1380, 4462, 3840, 1452, 2849, 3145, 1271, 1021,
            ...
             705, 3468, 4373, 1033, 4859, 4931, 3264, 1653, 2607, 2732],
           dtype='int64', length=3620)


In [80]:
# Preparación del conjunto de entrenamiento (conversión a matriz numpy)
train_matrix = train_data.values[:,:-1]
train_labels = train_data.values[:,-1]

# Preparación del conjunto de validación (conversión a matriz numpy)
test_matrix = test_data.values[:,:-1]
test_labels = test_data.values[:,-1]

#print(train_matrix)
#print(train_labels)
#print(test_matrix)
#print(test_labels)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [78]:
# Proponemos los siguientes clasificadores
bernoulli_classifier = BernoulliNB(binarize = 1.0)
normal_classifier = GaussianNB()
multinomial_classifier = MultinomialNB()

# Entrenamiento
print(bernoulli_classifier.fit(train_matrix,train_labels))
print(normal_classifier.fit(train_matrix,train_labels))
print(multinomial_classifier.fit(train_matrix,train_labels))

BernoulliNB(alpha=1.0, binarize=1.0, class_prior=None, fit_prior=True)
GaussianNB(priors=None, var_smoothing=1e-09)
MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)


In [79]:
# Pruebas en el conjunto de validación
test_bernoulli = bernoulli_classifier.predict(test_matrix)
test_normal = normal_classifier.predict(test_matrix)
test_multinomial = multinomial_classifier.predict(test_matrix)

# Pruebas en el conjunto de validación
train_bernoulli = bernoulli_classifier.predict(train_matrix)
train_normal = normal_classifier.predict(train_matrix)
train_multinomial = multinomial_classifier.predict(train_matrix)

def classification_errors(predicted,real):
    s = 0
    for i in range(0,len(predicted)):
        if predicted[i] != real[i]:
            s += 1
    return s

print('Sobre el conjunto de validación')    
print(classification_errors(test_bernoulli,test_labels))
print(classification_errors(test_normal,test_labels))
print(classification_errors(test_multinomial,test_labels))

print('Sobre el conjunto de entrenamiento')
print(classification_errors(train_bernoulli,train_labels))
print(classification_errors(train_normal,train_labels))
print(classification_errors(train_multinomial,train_labels))

Sobre el conjunto de validación
235
119
81
Sobre el conjunto de entrenamiento
490
226
166
