In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

# Import own libraries with custom technical routines and implemented logistic regression
from custom_routines import custom_routines as cr
from logisticReg import logistic_regression

# Import Naive Bayes classifiers from sci-kit learn
from sklearn.naive_bayes import MultinomialNB, GaussianNB

## 1. Clasificación de spam

In [2]:
spam_data = pd.read_csv("~/Desktop/mcc20192/mlearning/tareas/tarea3/data/spam.csv", header=None, delimiter=" ").values
print(len(spam_data))
#Partición aleatoria del conjunto de datos, 70% para entrenamiento y 30% para validación
train_spam_data, test_spam_data = train_test_split(spam_data, test_size=0.30, random_state=0)
print(len(train_spam_data),len(test_spam_data))

5172
3620 1552


In [3]:
multinomial_classifier = MultinomialNB()

multinomial_classifier.fit(train_spam_data[0:,:-1], train_spam_data[0:,-1])
print(multinomial_classifier.score(train_spam_data[0:,:-1], train_spam_data[0:,-1]))
print(multinomial_classifier.score(test_spam_data[0:,:-1], test_spam_data[0:,-1]))

0.9541436464088398
0.9478092783505154


In [4]:
# Train logistic regression 
logit_reg1 = logistic_regression()
logit_reg1.fit(train_spam_data[0:,:-1],train_spam_data[0:,-1],0)

In [5]:
print(logit_reg1.score(train_spam_data[0:,:-1],train_spam_data[0:,-1]))
print(logit_reg1.score(test_spam_data[0:,:-1],test_spam_data[0:,-1]))

0.9941988950276243
0.9639175257731959


## 2. Clasificación de tumores de seno

In [6]:
cancer_data_raw = pd.read_csv("~/Desktop/mcc20192/mlearning/tareas/tarea3/data/breast-cancer-wisconsin.data", header=None).values[0:,1:]
print(cancer_data_raw)

[[5 1 1 ... 1 1 2]
 [5 4 4 ... 2 1 2]
 [3 1 1 ... 1 1 2]
 ...
 [5 10 10 ... 10 2 4]
 [4 8 6 ... 6 1 4]
 [4 8 8 ... 4 1 4]]


In [12]:
#Sustituir valores desconocidos por 0 y cambiar las etiquetas por 0 y 1
n = len(cancer_data_raw)
l = len(cancer_data_raw[0])
cancer_data = np.ndarray(shape = (n,l))
type(cancer_data[0][0])

for i in range(0, n):
    for j in range(0, l-1):
        if cancer_data_raw[i][j] == '?':
            cancer_data[i][j] = 0
        else:
            cancer_data[i][j] = int(cancer_data_raw[i][j])
    cancer_data[i][-1] = int(cancer_data_raw[i][-1]/2 -1)

print(cancer_data)

#Partición aleatoria del conjunto de datos, 70% para entrenamiento y 30% para validación
train_cancer_data, test_cancer_data = train_test_split(cancer_data, test_size=0.30, random_state=0)
print(len(train_cancer_data),len(test_cancer_data))

[[ 5.  1.  1. ...  1.  1.  0.]
 [ 5.  4.  4. ...  2.  1.  0.]
 [ 3.  1.  1. ...  1.  1.  0.]
 ...
 [ 5. 10. 10. ... 10.  2.  1.]
 [ 4.  8.  6. ...  6.  1.  1.]
 [ 4.  8.  8. ...  4.  1.  1.]]
489 210


In [13]:
gaussian_classifier = GaussianNB()

# Entrenamos el clasificador
print(gaussian_classifier.fit(train_cancer_data[0:,:-1], train_cancer_data[0:,-1]))

GaussianNB(priors=None, var_smoothing=1e-09)


In [15]:
gaussian_classifier.score(test_cancer_data[0:,:-1],test_cancer_data[0:,-1])

0.9380952380952381

In [16]:
# Train logistic regression 
logit_reg2 = logistic_regression()
logit_reg2.fit(train_cancer_data[0:,:-1], train_cancer_data[0:,-1],0)

In [17]:
print(logit_reg2.score(train_cancer_data[0:,:-1], train_cancer_data[0:,-1]))
print(logit_reg2.score(test_cancer_data[0:,:-1], test_cancer_data[0:,-1]))

0.8711656441717791
0.8571428571428571
